language: java
sudo: true
jdk: openjdk8
services: postgresql
env:
  global:
    - BLUEGENES_DEFAULT_SERVICE_ROOT="http://localhost:8080/biotestmine"
    - CYPRESS_defaultCommandTimeout=60000
    - CYPRESS_requestTimeout=60000
    - CYPRESS_responseTimeout=60000

before_script:
  # Setup biotestmine to test against
  - git clone https://github.com/intermine/ci-scripts
  - (cd ci-scripts && bash init-biotestmine.sh)
  # Install lein - required to build the project
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /tmp/lein
  - chmod +x /tmp/lein
  - export PATH=$PATH:/tmp/lein
  # make several attempts at downloading dependencies
  - travis_retry lein deps
  # check code is well formatted
  - lein cljfmt check
  # start server
  - lein trampoline with-profile prod run &
  # install link validator bot for docs
  - gem install awesome_bot
  # install cypress dependencies
  - sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 -y


script:
  # setup dependencies
  - npm install
  # Run unit tests
  - lein kaocha
  # Build CSS
  - lein with-profile prod less once
  # ensure a minified build completes without error
  - lein with-profile prod cljsbuild once min
  # run UI tests using Cypress
  - npx cypress run
  # check for the links in the documentation
  - awesome_bot docs/*.md --allow-dupe --allow-redirect -w localhost
  # build API docs
  - lein with-profile prod codox

# Deploys build API docs:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: target/doc
  on:
    branch: dev
