language: generic
sudo: required

before_script:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /tmp/lein
  - chmod +x /tmp/lein
  - export PATH=$PATH:/tmp/lein
  - lein cljfmt check

script:
  - npm install
  - lein less once
  - lein cljsbuild once min
